system:
  ip: ""
  port: 8080
  env: dev
  gin_mode: debug
log:
  app: blogx_server
  dir: logs
jwt:
  expire: 3
  secret: xxx
  issuer: liangning
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 2
db:
  user: root
  password: liangningMySql123
  host: 127.0.0.1
  port: 3306
  db: blogx
  debug: false
  source: mysql
db1:
  user: root
  password: liangningMySql123
  host: 127.0.0.1
  port: 3306
  db: blogx
  debug: false
  source: mysql
upload:
  size: 3
  whiteList:
    - jpg
    - jpeg
    - png
    - webp
    - gif
  uploadDir: images001
site:
  siteInfo:
    title: 凉柠博客
    logo: ""
    beian: ""
    mode: 1
  project:
    title: ""
    icon: ""
    webPath: ""
  seo:
    keywords: ""
    description: ""
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: false
    emailLogin: false
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: true
email:
  domain: ""
  port: 0
  sendEmail: ""
  authCode: ""
  sendNickname: ""
  ssl: false
  tls: false
qq:
  appID: "747573454"
  appKey: ""
  redirect: http://xxxxx
qiNiu:
  enable: true
  accessKey: xsjtIqP8FGl1ylOEj5BqnvOdRMc6nrL4jIl0DK5D
  secretKey: 
  bucket: liangningblog
  uri: http://sqa480fov.sabkt.gdipper.com
  region: as0
  prefix: blogx
  size: 3
  expire: 60
ai:
  enable: false
  secretKey: njdfnhj6344t45347gsdhgsdh
  nickname: 凉柠
  avatar: /xxx/xxx
