system:
  ip: ""
  port: 8080
  env: dev
  gin_mode: debug
log:
  app: blogx_server
  dir: logs
jwt:
  expire: 3
  secret: xxx
  issuer: liangning
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 2
db:
  - user: root
    password: liangningMySql123
    host: 127.0.0.1
    port: 3306
    db: blogx
    debug: false
    source: mysql
  - user: root
    password: liangningMySql123
    host: 127.0.0.1
    port: 3306
    db: blogx
    debug: false
    source: mysql
es:
  url: http://127.0.0.1:9200
  username:
  password:
upload:
  size: 3
  whiteList:
    - jpg
    - jpeg
    - png
    - webp
    - gif
  uploadDir: images001
site:
  siteInfo:
    title: 凉柠博客
    logo: ""
    beian: ""
    mode: 1
  project:
    title: ""
    icon: ""
    webPath: ""
  seo:
    keywords: ""
    description: ""
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: true
    emailLogin: true
    captcha: true
  indexRight:
    list:
      - title: 独家推广
        enable: true
      - title: 用户反馈
        enable: true
      - title: 标签云
        enable: true
      - title: 文章推荐
        enable: true
      - title: 关于我们
        enable: true
      - title: 作者推荐
        enable: true
  article:
    noExamine: true
    commentLine: 2
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 1075090027@qq.com
  authCode:
  sendNickname: LiangNing
  ssl: true
  tls: false
qq:
  appID: "747573454"
  appKey: ""
  redirect: http://xxxxx
qiNiu:
  enable: true
  accessKey:
  secretKey:
  bucket: liangningblog
  uri: http://sqa480fov.sabkt.gdipper.com
  region: as0
  prefix: blogx
  size: 3
  expire: 60
ai:
  enable: false
  secretKey:
  nickname: 凉柠
  avatar: /xxx/xxx